- name: "ROOT"
  ansible.builtin.import_playbook: ./playbooks/root.yaml
- name: "TLDD"
  ansible.builtin.import_playbook: ./playbooks/tldd.yaml
- name: "AUTH"
  ansible.builtin.import_playbook: ./playbooks/auth.yaml
- name: "RECR"
  ansible.builtin.import_playbook: ./playbooks/recr.yaml
- name: "STUB"
  ansible.builtin.import_playbook: ./playbooks/stub.yaml
